config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :attachments do
    collection do
      get :add_attachment_to_form
    end
  end

  resources :assets

  resources :feedbacks

  resources :options_city_lists

  resources :location_options

  resources :galleries

  resources :media

  resources :reviews

  resources :service_locations

  resources :watched_posts

  resources :messages

  resources :conversations

  resources :authentications
  get '/auth/:provider/callback' => 'authentications#create'
  get '/auth/:provider/' => 'authentications#create', :as => :auth

  resources :bids do
    member do
      get :accept
      get :decline
    end
  end

  resources :comments

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings

  get 'change_status' => 'bids#change_status', :as => :change_status
  resources :timed_tasks

  resources :email_notification_settings

  resources :activities
  resources :personal_infos

  resources :posts do
    member do 
      get :activate_post
      get :all_bids
    end
  end

  get 'pages/home'
  get 'admin' => 'pages#admin', :as => "admin"
  get 'forgotten_password' => 'pages#forgotten_password', :as => :forgotten_password
  post 'reset_password' => 'pages#reset_password', :as => :reset_password
  resources :consumers

  match 'fetch_categories' => 'api#fetch_categories', as: :fetch_categories, via: [:get, :post]
  match 'fetch_subcategories' => 'api#fetch_subcategories', as: :fetch_subcategories, via: [:get, :post]
  match 'fetch_cities' => 'api#fetch_cities', as: :fetch_cities, via: [:get, :post]
  match 'fetch_provinces' => 'api#fetch_provinces', as: :fetch_provinces, via: [:get, :post]
  match 'fetch_subcategory' => 'api#fetch_subcategory', as: :fetch_subcategory, via: [:get, :post]

  resources :vendors

  resources :users do
    member do
      get :show_account
      get :overview
      get :inbox
      get :bids
      get :statistics
      get :profile
      get :account
      get :watched_posts
      get :read
      get :manage_posts
    end
  end
  resources :user_sessions, only: [:new, :create]
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/service_location.rb
class ServiceLocation < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :city
end

app/controllers/service_locations_controller.rb
class ServiceLocationsController < ApplicationController
  before_action :set_service_location, only: [:show, :edit, :update, :destroy]

  # GET /service_locations
  # GET /service_locations.json
  def index
    @service_locations = ServiceLocation.all
  end

  # GET /service_locations/1
  # GET /service_locations/1.json
  def show
  end

  # GET /service_locations/new
  def new
    @service_location = ServiceLocation.new
  end

  # GET /service_locations/1/edit
  def edit
  end

  # POST /service_locations
  # POST /service_locations.json
  def create
    @service_location = ServiceLocation.new(service_location_params)

    respond_to do |format|
      if @service_location.save
        format.html { redirect_to @service_location, notice: 'Service location was successfully created.' }
        format.json { render :show, status: :created, location: @service_location }
      else
        format.html { render :new }
        format.json { render json: @service_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_locations/1
  # PATCH/PUT /service_locations/1.json
  def update
    respond_to do |format|
      if @service_location.update(service_location_params)
        format.html { redirect_to @service_location, notice: 'Service location was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_location }
      else
        format.html { render :edit }
        format.json { render json: @service_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_locations/1
  # DELETE /service_locations/1.json
  def destroy
    @service_location.destroy
    respond_to do |format|
      format.html { redirect_to service_locations_url, notice: 'Service location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_location
      @service_location = ServiceLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_location_params
      params.require(:service_location).permit(:vendor_id, :city_id)
    end
end

app/helpers/service_locations_helper.rb
module ServiceLocationsHelper
end

app/views/service_locations/_form.html.haml
= form_for @service_location do |f|
  - if @service_location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service_location.errors.count, "error")} prohibited this service_location from being saved:"
      %ul
        - @service_location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :vendor_id
    = f.number_field :vendor_id
  .field
    = f.label :city_id
    = f.number_field :city_id
  .actions
    = f.submit 'Save'

app/views/service_locations/edit.html.haml
%h1 Editing service_location

= render 'form'

= link_to 'Show', @service_location
\|
= link_to 'Back', service_locations_path

app/views/service_locations/index.html.haml
%h1 Listing service_locations

%table
  %tr
    %th Vendor
    %th City
    %th
    %th
    %th

  - @service_locations.each do |service_location|
    %tr
      %td= service_location.vendor_id
      %td= service_location.city_id
      %td= link_to 'Show', service_location
      %td= link_to 'Edit', edit_service_location_path(service_location)
      %td= link_to 'Destroy', service_location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Service location', new_service_location_path

app/views/service_locations/new.html.haml
%h1 New service_location

= render 'form'

= link_to 'Back', service_locations_path

app/views/service_locations/show.html.haml
%p#notice= notice

%p
  %b Vendor:
  = @service_location.vendor_id
%p
  %b City:
  = @service_location.city_id

= link_to 'Edit', edit_service_location_path(@service_location)
\|
= link_to 'Back', service_locations_path