config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :attachments do
    collection do
      get :add_attachment_to_form
    end
  end

  resources :assets

  resources :feedbacks

  resources :options_city_lists

  resources :location_options

  resources :galleries

  resources :media

  resources :reviews

  resources :service_locations

  resources :watched_posts

  resources :messages

  resources :conversations

  resources :authentications
  get '/auth/:provider/callback' => 'authentications#create'
  get '/auth/:provider/' => 'authentications#create', :as => :auth

  resources :bids do
    member do
      get :accept
      get :decline
    end
  end

  resources :comments

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings

  get 'change_status' => 'bids#change_status', :as => :change_status
  resources :timed_tasks

  resources :email_notification_settings

  resources :activities
  resources :personal_infos

  resources :posts do
    member do 
      get :activate_post
      get :all_bids
    end
  end

  get 'pages/home'
  get 'admin' => 'pages#admin', :as => "admin"
  get 'forgotten_password' => 'pages#forgotten_password', :as => :forgotten_password
  post 'reset_password' => 'pages#reset_password', :as => :reset_password
  resources :consumers

  match 'fetch_categories' => 'api#fetch_categories', as: :fetch_categories, via: [:get, :post]
  match 'fetch_subcategories' => 'api#fetch_subcategories', as: :fetch_subcategories, via: [:get, :post]
  match 'fetch_cities' => 'api#fetch_cities', as: :fetch_cities, via: [:get, :post]
  match 'fetch_provinces' => 'api#fetch_provinces', as: :fetch_provinces, via: [:get, :post]
  match 'fetch_subcategory' => 'api#fetch_subcategory', as: :fetch_subcategory, via: [:get, :post]

  resources :vendors

  resources :users do
    member do
      get :show_account
      get :overview
      get :inbox
      get :bids
      get :statistics
      get :profile
      get :account
      get :watched_posts
      get :read
      get :manage_posts
    end
  end
  resources :user_sessions, only: [:new, :create]
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
has_many :participant_lists
has_many :users, through: :participant_lists
has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:subject, :last_msg)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.haml
= form_for @conversation do |f|
  - if @conversation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@conversation.errors.count, "error")} prohibited this conversation from being saved:"
      %ul
        - @conversation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :string
    = f.text_field :string
  .actions
    = f.submit 'Save'

app/views/conversations/edit.html.haml
%h1 Editing conversation

= render 'form'

= link_to 'Show', @conversation
\|
= link_to 'Back', conversations_path

app/views/conversations/index.html.haml
%h1 Listing conversations

%table
  %tr
    %th Subject
    %th String
    %th
    %th
    %th

  - @conversations.each do |conversation|
    %tr
      %td= conversation.subject
      %td= conversation.string
      %td= link_to 'Show', conversation
      %td= link_to 'Edit', edit_conversation_path(conversation)
      %td= link_to 'Destroy', conversation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Conversation', new_conversation_path

app/views/conversations/new.html.haml
%h1 New conversation

= render 'form'

= link_to 'Back', conversations_path

app/views/conversations/show.html.haml
= render 'layouts/includeScroll'
- @convo =  @conversation 
- @message = Message.new
.custom.container
  .column-names
    .col-xs-10.names-row.padding-left-30
      Message
    .col-xs-2.names-row
      Status
  .convo-container
    .convo-title
    
    .message-list
      - @convo.messages.each do |m|
        .other.message
          .img-container
            - if m.user.profile_pic == nil
              = image_tag ("//placehold.it/60x60"), class: "img-circle"
            -else
              - @image = m.user.profile_pic.image
              = image_tag @image.url(:small), class: "img-circle" 
            .username
              = m.user.first_name
          .text
            = m.info


    = render 'messages/form'