config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :attachments do
    collection do
      get :add_attachment_to_form
    end
  end

  resources :assets

  resources :feedbacks

  resources :options_city_lists

  resources :location_options

  resources :galleries

  resources :media

  resources :reviews

  resources :service_locations

  resources :watched_posts

  resources :messages

  resources :conversations

  resources :authentications
  get '/auth/:provider/callback' => 'authentications#create'
  get '/auth/:provider/' => 'authentications#create', :as => :auth

  resources :bids do
    member do
      get :accept
      get :decline
    end
  end

  resources :comments

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings

  get 'change_status' => 'bids#change_status', :as => :change_status
  resources :timed_tasks

  resources :email_notification_settings

  resources :activities
  resources :personal_infos

  resources :posts do
    member do 
      get :activate_post
      get :all_bids
    end
  end

  get 'pages/home'
  get 'admin' => 'pages#admin', :as => "admin"
  get 'forgotten_password' => 'pages#forgotten_password', :as => :forgotten_password
  post 'reset_password' => 'pages#reset_password', :as => :reset_password
  resources :consumers

  match 'fetch_categories' => 'api#fetch_categories', as: :fetch_categories, via: [:get, :post]
  match 'fetch_subcategories' => 'api#fetch_subcategories', as: :fetch_subcategories, via: [:get, :post]
  match 'fetch_cities' => 'api#fetch_cities', as: :fetch_cities, via: [:get, :post]
  match 'fetch_provinces' => 'api#fetch_provinces', as: :fetch_provinces, via: [:get, :post]
  match 'fetch_subcategory' => 'api#fetch_subcategory', as: :fetch_subcategory, via: [:get, :post]

  resources :vendors

  resources :users do
    member do
      get :show_account
      get :overview
      get :inbox
      get :bids
      get :statistics
      get :profile
      get :account
      get :watched_posts
      get :read
      get :manage_posts
    end
  end
  resources :user_sessions, only: [:new, :create]
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :owner, polymorphic: true
  has_attached_file :image, :styles => {:post_media => "225x150#",:vendor_cover => "970x385#",:vendor_media =>"120x120#", :medium => "300x300>", :thumb => "100x100>",:profile => "200x200>",:small => "70X70#", :full => "1000X670>", :index => "180X191#" }  
  validates_attachment_size :image, :less_than => 75.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  # before_create :update_file_name

  private

  # change file name to vendor_name_#
  # def update_file_name
  #   new_name = self.owner.user.first_name.downcase.tr(" ", "_") + "_"
  #   number = Asset.last.nil? ? "1" : (Asset.last.id + 1).to_s
  #   extension = File.extname(image_file_name).downcase
 #   self.image.instance_write(:file_name, new_name + number + extension)
  # end
  def to_jq_upload
    {
      "name" => read_attribute(:image_file_name),
      "size" => read_attribute(:image_file_size)
    }
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  def add_attachment_to_form
    @target = params[:target]
    @attachment = Attachment.new
    respond_to do |format|
      format.js
    end
  end
  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.create(attachment_params)
    @link = attachment_params["embedded_id"]
    if @link != "" && @link != nil
      if @link.include? "embed"
        @index =  @link.index('src=')
        @index =  @index + 35
        @final = @index + 11
        @embedded = ""
        while @index < @final
          @embedded = @embedded + @link[@index]
          @index = @index + 1
        end
        @attachment.embedded_id = @embedded
        @attachment.save
      elsif @link.include? "watch?v="
        if @link.split("watch?v=")[1].length() == 11
          @attachment.embedded_id = @link.split("watch?v=")[1]
          @attachment.save
        end
      elsif @link.include? "youtu.be"
        @attachment.embedded_id = @link.split('youtu.be/')[1]
        @attachment.save
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @id = @attachment.id
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:owner_id, :owner_type, :image, :embedded_id)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.haml
- @attachment = Attachment.new

= form_for(@attachment, html: { multipart: true }) do |f|
  = f.hidden_field :owner_id, value: gallery.id
  = f.hidden_field :owner_type, value: "Gallery"
  = f.hidden_field :multipe_files, value: true
  = f.file_field :image, multiple: false, name: 'attachment[image]', id: "image-input-#{gallery.id}", class: "hidden"
  %label{for: "image-input-#{gallery.id}", class: "file-upload-#{gallery.name}"}
    - if !gallery.attachments.empty?
      - @url = gallery.attachments.last.image.url
    - else
      - @url = nil

    .file-upload-container{class: "#{'file-upload-btn' if gallery.attachments.empty? } file-upload-#{gallery.name}",  style: "background-image: url(#{@url})"}
      .progress-bar
      - if !gallery.attachments.empty?
        - @last_attachment = gallery.attachments.last
        -# = link_to "X", @last_attachment, method: :delete, confirm: 'Delete?', remote:true, class: "destroy-attachment"

      - if gallery.attachments.empty?
        %span#wrapper
          = attachment_text
      - else
        .upload-btn
          %i.fa.fa-camera
          Change Image

app/views/attachments/_media_upload_button.html.haml
%label{for: "image-input-#{gallery.id}"}
  .file-upload-container.file-upload-btn
    .progress-bar
    %span#wrapper  Add A Picture To Your Media 

app/views/attachments/_multiple_attachments.html.haml
.

app/views/attachments/_multiple_form.html.haml
- @attachment = Attachment.new
- if gallery == nil
  - @gallery = @vendor.media
-else
  - @gallery = gallery
= form_for(@attachment, html: { multipart: true }, remote:true) do |f|
  = f.hidden_field :owner_id, value: @gallery.id
  = f.hidden_field :owner_type, value: "Gallery"
  = f.hidden_field :multipe_files, value: true
  = f.file_field :image, multiple: false, name: 'attachment[image]', id: "image-input-#{gallery.id}", class: "hidden"
  - if @gallery != nil
    - @gallery.attachments.each do |attachment|

      %label
        - if attachment.embedded_id != ""

          .file-upload-container{  style: "background-image: url(http://img.youtube.com/vi/#{attachment.embedded_id}/default.jpg)"}
            = link_to "X", attachment, method: :delete, confirm: 'Delete?', remote:true, class: "destroy-attachment"
            %span.centered-icon
              %i.fa.fa-youtube-play
        - else
          .file-upload-container{  style: "background-image: url(#{attachment.image.url})"}
            = link_to "X", attachment, method: :delete, confirm: 'Delete?', remote:true, class: "destroy-attachment"
  = render 'attachments/media_upload_button', gallery:@gallery
  .col-xs-12.no-h-padding.not-centered.embedded-link-container
    = f.text_field :embedded_id , class: "col-xs-10 no-h-padding embbedded-submit"
    = f.submit "Add Video Link", class: "next col-xs-2 no-h-padding"
        

app/views/attachments/_multiple_post.html.haml
- @attachment = Attachment.new
- @post = post
= form_for(@attachment, html: { multipart: true }) do |f|
  = f.hidden_field :owner_id, value: post.id
  = f.hidden_field :owner_type, value: "Post"
  = f.hidden_field :multipe_files, value: true
  = f.hidden_field :active, value: true
  = f.file_field :image, multiple: false, name: 'attachment[image]', id: "image-input-#{post.id}", class: "hidden"
  - if @post != nil
    - @post.attachments.each do |attachment|
      %label
        .file-upload-container{  style: "background-image: url(#{attachment.image.url})"}
          = link_to "X", attachment, method: :delete, confirm: 'Delete?', remote:true, class: "destroy-attachment"
  %label{for: "image-input-#{post.id}"}
    .file-upload-container.file-upload-btn
      .progress-bar
      %span#wrapper  Add A Picture To Your Post
.col-xs-12.button
  = form_for @post do |p|
    = p.hidden_field :active, value: true
    = p.submit 'Post', class: "next submit"

app/views/attachments/_show_attachment.js.erb
$

app/views/attachments/add_attachment_to_form.js.erb
$(document).ready(function(){
  $("<%= @target %>").append("<%=j render partial: 'attachments/form', locals: { gallery: @gallery } %>")
  console.log('test')
})

app/views/attachments/create.js.erb
$('#loadmodal').hide();
<% if @attachment.owner_type == "Gallery" %>
  $('.gallery-container-<%=@attachment.owner.id%>').find('form').remove();
  $('#loadmodal').hide();
  console.log('updated');
  <% if @attachment.owner.name == 'Profile_Pictures' || @attachment.owner.name == "Cover_Pictures" %>
    $('.gallery-container-<%=@attachment.owner.id%>').append("<%=j render partial: 'attachments/form', locals: { attachment: @attachment, gallery: @attachment.owner } %>")
  <%elsif @attachment.owner.name == "Media" %>
    $('.media-gallery').empty()
    $('.media-gallery').append("<%=j render partial: 'attachments/multiple_form', locals: { attachment: @attachment, gallery: @attachment.owner } %>")
  <%end%> 
<%elsif @attachment.owner_type == "Post" %>
  $('.slide-3').empty();
  $('.slide-3').append("<%=j render partial: 'attachments/multiple_post', locals: { post: @attachment.owner } %>")
<%end%>
$('.new_attachment').each(function() {
  $(this).fileupload({
    dataType: 'script',
    add: function(e, data) {
      $('#loadmodal').show();
      var file, types;
      types = /(\.|\/)(gif|jpe?g|png|mov|mpeg|mpeg4|avi)$/i;
      file = data.files[0];
      if (types.test(file.type) || types.test(file.name)) {
        data.formData = $(this).serializeArray();
        $(this).find('.file-upload-container').children('span').text(file.name);
        $(this).find('.file-upload-container').addClass('in-progress');
        return setTimeout(data.submit(), 3000);
      } else {
        return alert(file.name + " is not a gif, jpg or png image file");
      }
    },
    progress: function(e, data) {
      var progress;
      if (data.context) {
        progress = parseInt(data.loaded / data.total * 100, 10);
        return $('.progress-bar').css('width', progress + '%');
      }
    },
    done: function(e, data) {
      return $('.actions input[type="submit"]').off('click');
    }
  });
});

app/views/attachments/edit.html.haml
%h1 Editing attachment

= render 'form'

= link_to 'Show', @attachment
\|
= link_to 'Back', attachments_path

app/views/attachments/index.html.haml
%h1 Listing attachments

%table
  %thead
    %tr
      %th Owner
      %th Owner type
      %th
      %th
      %th

  %tbody
    - @attachments.each do |attachment|
      %tr
        %td= attachment.owner_id
        %td= attachment.owner_type
        %td= link_to 'Show', attachment
        %td= link_to 'Edit', edit_attachment_path(attachment)
        %td= link_to 'Destroy', attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Attachment', new_attachment_path

app/views/attachments/new.html.haml
%h1 New attachment

= render 'form'

= link_to 'Back', attachments_path

app/views/attachments/show.html.haml
%p#notice= notice

%p
  %b Owner:
  = @attachment.owner_id
%p
  %b Owner type:
  = @attachment.owner_type

= link_to 'Edit', edit_attachment_path(@attachment)
\|
= link_to 'Back', attachments_path