config/routes.rb
Rails.application.routes.draw do

  resources :cities

  resources :attachments do
    collection do
      get :add_attachment_to_form
    end
  end

  resources :assets

  resources :feedbacks

  resources :options_city_lists

  resources :location_options

  resources :galleries

  resources :media

  resources :reviews

  resources :service_locations

  resources :watched_posts

  resources :messages

  resources :conversations

  resources :authentications
  get '/auth/:provider/callback' => 'authentications#create'
  get '/auth/:provider/' => 'authentications#create', :as => :auth

  resources :bids do
    member do
      get :accept
      get :decline
    end
  end

  resources :comments

  get 'notification_settings' => 'email_notification_settings#index', :as => :notification_settings

  get 'change_status' => 'bids#change_status', :as => :change_status
  resources :timed_tasks

  resources :email_notification_settings

  resources :activities
  resources :personal_infos

  resources :posts do
    member do 
      get :activate_post
      get :all_bids
    end
  end

  get 'pages/home'
  get 'admin' => 'pages#admin', :as => "admin"
  get 'forgotten_password' => 'pages#forgotten_password', :as => :forgotten_password
  post 'reset_password' => 'pages#reset_password', :as => :reset_password
  resources :consumers

  match 'fetch_categories' => 'api#fetch_categories', as: :fetch_categories, via: [:get, :post]
  match 'fetch_subcategories' => 'api#fetch_subcategories', as: :fetch_subcategories, via: [:get, :post]
  match 'fetch_cities' => 'api#fetch_cities', as: :fetch_cities, via: [:get, :post]
  match 'fetch_provinces' => 'api#fetch_provinces', as: :fetch_provinces, via: [:get, :post]
  match 'fetch_subcategory' => 'api#fetch_subcategory', as: :fetch_subcategory, via: [:get, :post]

  resources :vendors

  resources :users do
    member do
      get :show_account
      get :overview
      get :inbox
      get :bids
      get :statistics
      get :profile
      get :account
      get :watched_posts
      get :read
      get :manage_posts
    end
  end
  resources :user_sessions, only: [:new, :create]
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'pages#home'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)
    respond_to do |format|
      if @feedback.save
        format.html { redirect_to root_path, notice: 'Thank you for giving us feedback!' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:email, :content, :fist_name, :last_name, :feedback_type)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.haml
= form_for @feedback do |f|
  - if @feedback.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feedback.errors.count, "error")} prohibited this feedback from being saved:"
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :fist_name
    = f.text_field :fist_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :feedback_type
    = f.text_field :feedback_type
  .actions
    = f.submit 'Save'

app/views/feedbacks/edit.html.haml
%h1 Editing feedback

= render 'form'

= link_to 'Show', @feedback
\|
= link_to 'Back', feedbacks_path

app/views/feedbacks/index.html.haml
%h1 Listing feedbacks

%table
  %thead
    %tr
      %th Email
      %th Content
      %th Fist name
      %th Last name
      %th Feedback type
      %th
      %th
      %th

  %tbody
    - @feedbacks.each do |feedback|
      %tr
        %td= feedback.email
        %td= feedback.content
        %td= feedback.fist_name
        %td= feedback.last_name
        %td= feedback.feedback_type
        %td= link_to 'Show', feedback
        %td= link_to 'Edit', edit_feedback_path(feedback)
        %td= link_to 'Destroy', feedback, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feedback', new_feedback_path

app/views/feedbacks/new.html.haml
%h1 New feedback

= render 'form'

= link_to 'Back', feedbacks_path

app/views/feedbacks/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @feedback.email
%p
  %b Content:
  = @feedback.content
%p
  %b Fist name:
  = @feedback.fist_name
%p
  %b Last name:
  = @feedback.last_name
%p
  %b Feedback type:
  = @feedback.feedback_type

= link_to 'Edit', edit_feedback_path(@feedback)
\|
= link_to 'Back', feedbacks_path